# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eb8a4ae3038689b48aaaa981da971e8418d278239e7bdffac0ae156cf546b67bedfd8a6a27d7ad8672cc05e0f7629948d0efbe4d37697734bb7bd9dc34a6194

test:
  secret_key_base: e47c66a8d81baf9478654e38971d9fb10e12d2b8f6aed18031599bf5e5f30a911d7ce38ac7de6279e31de2ba22ce21f1b86c9b69f44ce339a337c0ab278598ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
